// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM3a6y_LdDJD2Eeid1AJoD8_yOijYe8aI',
    appId: '1:126789181654:web:4015865aa14a1c08c42977',
    messagingSenderId: '126789181654',
    projectId: 'planttreatmonty-dfebf',
    authDomain: 'planttreatmonty-dfebf.firebaseapp.com',
    storageBucket: 'planttreatmonty-dfebf.firebasestorage.app',
    measurementId: 'G-QEB5WMBTH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrc6MnhUrByCSHywbywZarJTejSvpf8-8',
    appId: '1:126789181654:android:55431c0d377799afc42977',
    messagingSenderId: '126789181654',
    projectId: 'planttreatmonty-dfebf',
    storageBucket: 'planttreatmonty-dfebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtor9z3nKRA0lWlKekBK8A4yb05I0B3fU',
    appId: '1:126789181654:ios:742d808ea18090b0c42977',
    messagingSenderId: '126789181654',
    projectId: 'planttreatmonty-dfebf',
    storageBucket: 'planttreatmonty-dfebf.firebasestorage.app',
    iosClientId: '126789181654-jnjatjnukhph077hje5i2k201bcfeie6.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantTreatmonty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtor9z3nKRA0lWlKekBK8A4yb05I0B3fU',
    appId: '1:126789181654:ios:742d808ea18090b0c42977',
    messagingSenderId: '126789181654',
    projectId: 'planttreatmonty-dfebf',
    storageBucket: 'planttreatmonty-dfebf.firebasestorage.app',
    iosClientId: '126789181654-jnjatjnukhph077hje5i2k201bcfeie6.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantTreatmonty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM3a6y_LdDJD2Eeid1AJoD8_yOijYe8aI',
    appId: '1:126789181654:web:7fca47ba6e684117c42977',
    messagingSenderId: '126789181654',
    projectId: 'planttreatmonty-dfebf',
    authDomain: 'planttreatmonty-dfebf.firebaseapp.com',
    storageBucket: 'planttreatmonty-dfebf.firebasestorage.app',
    measurementId: 'G-E2XV427NBH',
  );

}